package kz.amangeldy.currency

val currencyNameMap = mapOf(
    "BRL" to "Brazilian Real",
    "EUR" to "Euro",
    "AUD" to "Australian Dollar",
    "BGN" to "Bulgarian Lev",
    "CAD" to "Canadian Dollar",
    "CHF" to "Swiss Franc",
    "CNY" to "Yuan",
    "CZK" to "Czech Koruna",
    "DKK" to "Danish Kroner",
    "GBP" to "Pound Sterling",
    "HKD" to "Hong Kong Dollar",
    "HUF" to "Forint",
    "IDR" to "Rupiah",
    "ILS" to "New Israeli Sheqel",
    "INR" to "Indian Rupee",
    "ISK" to "Iceland Krona",
    "JPY" to "Yen",
    "HRK" to "Croatian kuna",
    "KRW" to "Won",
    "MXN" to "Mexican Peso",
    "MYR" to "Malaysian Ringgit",
    "NOK" to "Norwegian Krone",
    "NZD" to "New Zealand Dollar",
    "PHP" to "Philippine Peso",
    "PLN" to "Polish Zloty",
    "RON" to "Romanian leu",
    "RUB" to "Russian Ruble",
    "SEK" to "Swedish Krona",
    "SGD" to "Singapore Dollar",
    "THB" to "Thai Baht",
    "TRY" to "Yeni Türk Liras",
    "USD" to "US Dollar",
    "ZAR" to "South African Rand"
)

val currencyCountryFlag = mapOf(
    "BRL" to R.drawable.brazil,
    "EUR" to R.drawable.european_union,
    "AUD" to R.drawable.australia,
    "BGN" to R.drawable.bulgaria,
    "CAD" to R.drawable.canada,
    "CHF" to R.drawable.switzerland,
    "CNY" to R.drawable.ic_china,
    "CZK" to R.drawable.czech_republic,
    "DKK" to R.drawable.denmark,
    "GBP" to R.drawable.united_kingdom,
    "HKD" to R.drawable.hong_kong,
    "HUF" to R.drawable.hungary,
    "IDR" to R.drawable.indonesia,
    "HRK" to R.drawable.ic_croatia,
    "ILS" to R.drawable.israel,
    "INR" to R.drawable.india,
    "ISK" to R.drawable.iceland,
    "JPY" to R.drawable.japan,
    "KRW" to R.drawable.south_korea,
    "MXN" to R.drawable.mexico,
    "MYR" to R.drawable.malaysia,
    "NOK" to R.drawable.norway,
    "NZD" to R.drawable.new_zealand,
    "PHP" to R.drawable.philippines,
    "PLN" to R.drawable.republic_of_poland,
    "RON" to R.drawable.ic_romania,
    "RUB" to R.drawable.russia,
    "SEK" to R.drawable.sweden,
    "SGD" to R.drawable.singapore,
    "THB" to R.drawable.thailand,
    "TRY" to R.drawable.turkey,
    "USD" to R.drawable.united_states_of_america,
    "ZAR" to R.drawable.south_africa
)